kafka:
  bootstrapServers: 127.0.0.1:9092 # Estou especificando o servidor na qual o user se conectará nesse caso 9092
  acksConfig: all # A configuração do acks controla os critérios sob os quais as solicitações são consideradas concluídas
  retriesConfig: 10 # Determina quantas vezes o produtor tentará enviar uma mensagem antes de marcá-la como falhada
  schemaRegistryUrl: "http://127.0.0.1:8081" # Especifica a URL do registro de esquema Avro.
  maxPollRecordsConfig: 1 # O número máximo de registros retornados em uma única chamada

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/o8k_academy_db
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

server:
  port: 9090
